/** Declaration file generated by dts-gen */

declare class Driver {
    constructor(...args: any[]);

    initialize(...args: any[]): void;

}


declare namespace Driver {
    namespace prototype {
        function initialize(...args: any[]): void;

    }

}

