/** Declaration file generated by dts-gen */

declare class Elasticsearch {
    constructor(...args: any[]);

    count(...args: any[]): void;

    deleteById(...args: any[]): void;

    find(...args: any[]): void;

    initialize(...args: any[]): void;

    insert(...args: any[]): void;

    updateById(...args: any[]): void;

}


declare namespace Elasticsearch {
    namespace prototype {
        function count(...args: any[]): void;

        function deleteById(...args: any[]): void;

        function find(...args: any[]): void;

        function initialize(...args: any[]): void;

        function insert(...args: any[]): void;

        function updateById(...args: any[]): void;

    }

}

