/** Declaration file generated by dts-gen */

declare class Http {
    constructor(...args: any[]);

    initialize(...args: any[]): void;

}


declare namespace Http {
    namespace prototype {
        function initialize(...args: any[]): void;

    }

}

