/** Declaration file generated by dts-gen */

declare class Mysql {
    constructor(...args: any[]);

    deleteById(...args: any[]): void;

    find(...args: any[]): void;

    findById(...args: any[]): void;

    initialize(...args: any[]): void;

    insert(...args: any[]): void;

    insertMany(...args: any[]): void;

    startTransaction(...args: any[]): void;

    update(...args: any[]): void;

    updateById(...args: any[]): void;

}


declare namespace Mysql {
    namespace prototype {
        function deleteById(...args: any[]): void;

        function find(...args: any[]): void;

        function findById(...args: any[]): void;

        function initialize(...args: any[]): void;

        function insert(...args: any[]): void;

        function insertMany(...args: any[]): void;

        function startTransaction(...args: any[]): void;

        function update(...args: any[]): void;

        function updateById(...args: any[]): void;

    }

}

