/** Declaration file generated by dts-gen */

declare class Redis {
    constructor(...args: any[]);

    initialize(...args: any[]): void;

}


declare namespace Redis {
    namespace prototype {
        function initialize(...args: any[]): void;

    }

}

