/** Declaration file generated by dts-gen */

declare namespace index {
    function error404(req: any, res: any, next: any): void;

    function errors(err: any, req: any, res: any, next: any): void;

    function loggerRequests(loggerFunction: any, extractRequest: any): any;
}


export = index;