/** Declaration file generated by dts-gen */

declare function loggerRequests(loggerFunction: any, extractRequest: any): any;


declare namespace loggerRequests {
    const prototype: {
    };

}

