/** Declaration file generated by dts-gen */

declare class Crypt {
    constructor(...args: any[]);

    decrypt(...args: any[]): void;

    encrypt(...args: any[]): void;

}


declare namespace Crypt {
    namespace prototype {
        function decrypt(...args: any[]): void;

        function encrypt(...args: any[]): void;

    }

}

