/** Declaration file generated by dts-gen */

declare class BaseModel {
    constructor(...args: any[]);

    setDataSouce(...args: any[]): void;

    setPrimaryKey(...args: any[]): void;

    setTable(...args: any[]): void;

}


declare namespace BaseModel {
    namespace prototype {
        function setDataSouce(...args: any[]): void;

        function setPrimaryKey(...args: any[]): void;

        function setTable(...args: any[]): void;

    }

}

