/** Declaration file generated by dts-gen */

declare namespace index {
    function date(pattern: any): any;

    function deepFreeze(object: any): any;

    namespace date {
        const prototype: {
        };

    }

    namespace deepFreeze {
        const prototype: {
        };

    }

}

